// const API_PROXY_PREFIX='/api'
// const BASE_URL = process.env.NODE_ENV === 'production' ? process.env.VUE_APP_API_BASE_URL : API_PROXY_PREFIX
const BASE_URL = process.env.VUE_APP_API_BASE_URL;
module.exports = {
    REQUEST_LOGIN: `${BASE_URL}/request-login`,
    LOGIN: `${BASE_URL}/login`,
    PROFILE: `${BASE_URL}/profile`,
    CHANGE_PASSWORD: `${BASE_URL}/change-password`,
    ROUTES: `${BASE_URL}/routes`,
    BASE_URL: `${BASE_URL}`,
    USER: `${BASE_URL}/user-admin`,
    USER_GROUP: `${BASE_URL}/user-group`,
    QUAN_TRI_VIEN: `${BASE_URL}/admin`,
    NHA_PHAN_PHOI: `${BASE_URL}/distributor`,
    DAI_LY: `${BASE_URL}/agent`,
    KHACH_MUA_HANG: `${BASE_URL}/khach-hang`,
    BAO_GIA: `${BASE_URL}/bao-gia`,
    TRANG_THAI_BAO_GIA: `${BASE_URL}/trang-thai-bao-gia`,
    CUSTOMER: `${BASE_URL}/customer`,
    CHANGE_CUSTOMER: `${BASE_URL}/change-customer`,
    CUSTOMER_GROUP: `${BASE_URL}/customer-group`,
    CUSTOMER_GROUP_MEMBERS: `${BASE_URL}/customer-group-members`,
    KICKOUT_CUSTOMER: `${BASE_URL}/kickout-customer`,
    GATEWAY: `${BASE_URL}/gateway`,
    ENTITY: `${BASE_URL}/entity`,
    IMPORT_PRODUCT: `${BASE_URL}/import-product`,
    PRODUCT: `${BASE_URL}/product`,
    UNG_DUNG: `${BASE_URL}/app`,
    PHIEN_BAN: `${BASE_URL}/version`,
    THONG_BAO: `${BASE_URL}/notification`,
    THONG_KE: `${BASE_URL}/report/client-online`,
    HINH_ANH: `${BASE_URL}/images`,
    HARDWARE: `${BASE_URL}/hardware`,
    FIRMWARE: `${BASE_URL}/firmware`,
    UPLOAD_FIRMWARE: `${BASE_URL}/upload-firmware`,
    RELEASE_FIRMWARE: `${BASE_URL}/release-firmware`,
    DISABLE_TEST_FIRMWARE: `${BASE_URL}/disable-test-firmware`,
    AGENT_DEVICE: `${BASE_URL}/agent-device`,
    DON_HANG: `${BASE_URL}/don-hang`
};
